#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  2 17:40:08 2022

@author: kimsubin
"""


lista = ["risk","issue", "test", "maintenanace", "maturity"]
vlista = ["security","plan", "test", "maintenanace", "satety"]
listc = ["maintenance", "verification", "validation"]

# docker practice example code
# hi
# hi